# 应用服务 WEB 访问端口
server:
  port: 8080

spring:
  profiles:
    # 默认激活开发环境
    active: dev

jwt:
  issuer: capybara349
  secret: zL3KH852ynMtDA5fR1GdmuSc1InmdvPlwjIBxd1GwU6QUDUN+vhrsMlNWeFc/mZaDjA91mOARNPxdIv6583xnA==